{
    'name': 'Haikvision Attendance Machine',
    'version': '1.1',
    'category': 'Human Resources',
    'summary': 'Live Hikvision Attendance Sync with Odoo',
    'license': 'LGPL-3',
    'author': 'TopTechnology',
    'depends': [
        'base',
        'web',
        'mail',
        'hr',
        'hr_attendance',
    ],
    'data': [
        'security/security_groups.xml',
        'security/security_rules.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/work_policy_data.xml',
        'views/search_views.xml',
        'views/hikvision_device_views.xml',
        'views/hikvision_user_views.xml',
        'views/attendance_views.xml',
        'views/employee_profile_views.xml',
        'views/action.xml',
        'views/employee_push_views.xml',
        'views/hikvision_event_log_views.xml',
        'views/fetch_logs_wizard_views.xml',
        'views/attendance_policy_views.xml',
        'views/policy_assign_wizard_views.xml',
        'views/hr_employee_views.xml',
        'views/service_view.xml',
        'views/menu.xml',  # Temporarily disabled due to XML validation error
    ],
    'installable': True,
    'application': True,
}
